const express = require("express");
const router = express.Router();

const authRoute = require("./auth.route");
const uploadRoute = require("./upload.route");
const categoryRoute = require("./category.route");
const productRoute = require("./product.route");
const pondRoute = require("./pond.route");
const cropSeasonRoute =require ("./cropSeason.route");
const customerProfileRoute = require("./customerProfile.route");
const orderRoute = require("./order.route");    
const paymentRoute = require("./payment.route");
const deliveryRoute = require("./delivery.route");
const faceRoute=require("./face.route");
const debtRoutes = require("./debt.route");
const debtExtensionRoute = require("./debtExtension.route");
const notificationRoute = require("./notification.route");

router.use("/notifications", notificationRoute);
router.use("/auth", authRoute);
router.use("/upload", uploadRoute);
router.use("/categories", categoryRoute);
router.use("/products", productRoute);
router.use("/ponds", pondRoute);
router.use("/crop-seasons", cropSeasonRoute);
router.use("/customer-profiles", customerProfileRoute);
router.use("/orders", orderRoute);
router.use("/payments", paymentRoute);
router.use("/deliveries", deliveryRoute);
router.use("/faces", faceRoute);
router.use("/debts", debtRoutes);
router.use("/debt-extensions", debtExtensionRoute);
module.exports = router;